version: '3.8'

services:
  frontend:
    build:
      context: ./roboclaim-hiring-task-fe
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  backend:
    build:
      context: ./roboclaim-hiring-task-be
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=production